# Generated by Django 4.1 on 2022-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
